### ISSUE TITLE
Truncate an existing file gives spurious error and unmounts filesystem

### ISSUE THREAD

**Issue by s-macke** [geky/littlefs-fuse#2]
When I try the commands 

```shell
mkdir -p mount
lfs --format /dev/loop0
lfs /dev/loop0 mount
cd mount
dd if=/dev/urandom of=temp bs=16 count=1
truncate -s 32 temp
```
on a existing loop block device I receive the error 

```
truncate: failed to truncate 'temp' at 32 bytes: Numerical result out of range
```
Also the filesystem is unmounted afterwards.

**Comment by geky** [comment]
Thanks for raising the issue. Looks like it was a bad error code check in `lfs_file_truncate`. Does this fix work for you?
https://github.com/geky/littlefs-fuse/tree/fix-truncate-err

I'll get the fix upstreamed when I can.

**Comment by s-macke** [comment]
The problem is indeed fixed. However, there are still other very basic problems with this filesystem or the FUSE implementation. Especially returning wrong file sizes and stopping during a read process.

I wrote a tiny test tool to check the basic functionality of filesystems. Nothing fancy. Just random, writes, reads and renames, ....

https://github.com/s-macke/CoverFS/blob/master/tests/checkfragment.cpp

Anyhow this specific problem is solved.

**Comment by geky** [comment]
Well we can always improve. Thanks for the script, I'll have to see if we can clean up the errors. I should probably get a posix test suite running on this guy.

**Comment by geky** [comment]
Sorry for the delay, CI caught a bug when I tried to update (https://github.com/geky/littlefs/commit/e611cf5050fc44acb97057654b6885ec9b060915). This fix should be on master now.
